name: "ShellCheck"
permissions:
  contents: read

on:
  push:
    paths: [ "**/*.sh" ]
  pull_request:
    paths: [ "**/*.sh" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          check_together: true
      - name: Check formatting with shfmt
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shfmt
          shfmt -d .